[lint]
select = ["I", "TCH", "PLC", "PLE"]
# extend-select = ["ALL"]

ignore  = ["E722", "F841", "E501"]
# E722 Do not use bare `except`
# F841 Local variable `xxx` is assigned to but never used
# E501 Line too long

[lint.per-file-ignores]
"sos_trades_api/server/*" = ["E402", "F403"]
"server_scripts/calculation/launch_calculation.py" = ["I001"]
