icon-mapping:
  data: fa-solid fa-folder fa-fw
  root: fa-solid fa-sitemap fa-fw
  SoSCoupling: fa-solid fa-cogs fa-fw
  Disc1: fa-solid fa-plane fa-fw
  Disc2: fa-solid fa-exchange fa-fw
  Disc3: fa-solid fa-money-bill-alt fa-fw
  ACModelDiscipline: fa-solid fa-plane fa-fw
  ACModelStatic: fa-solid fa-plane fa-fw
  NetworkDiscipline: fa-solid fa-exchange fa-fw
  EnergyModelsDiscipline: fa-solid fa-bolt fa-fw
  EnergyStaticDiscipline: fa-solid fa-bolt fa-fw
  EconomicsManufacturerDiscipline: fa-solid fa-industry fa-fw
  EconomicsOperatorDiscipline: fa-solid fa-group fa-fw
  MarketDiscipline: fa-solid fa-globe-americas fa-fw
  MarketSensitivityDiscipline: fa-solid fa-globe-americas fa-fw
  MarketSensitivityCOCDiscipline: fa-solid fa-globe-americas fa-fw
  StaticCoCDiscipline: fa-solid fa-file-invoice-dollar fa-fw
  ServiceMarketDicsipline: fa-solid fa-cubes fa-fw
  BusinessCaseDiscipline: fa-solid fa-money-bill-alt fa-fw
  BusinessDiscipline: fa-solid fa-money-bill-alt fa-fw
  BusinessMonoDiscipline: fa-solid fa-money-bill-alt fa-fw
  SoSMultiInstances: fa-solid fa-sliders fa-fw
  EconomicsAggregationDiscipline: fa-solid fa-line-chart fa-fw
  ServicesMarketDiscipline: fa-solid fa-book fa-fw
  ServicesDiscipline: fa-solid fa-chain fa-fw
  LCADiscipline: fa-solid fa-tree fa-fw
  GudmundssonRCDiscipline: fa-solid fa-line-chart fa-fw
  GudmundssonNRCDiscipline: fa-solid fa-line-chart fa-fw
  PostProcessingMarketDiscipline: fa-solid fa-globe-americas fa-fw
  PostProcessingEconomicsDiscipline: fa-solid fa-line-chart fa-fw
  PostProcessingServicesMarketDiscipline: fa-solid fa-book fa-fw
  PostProcessingBusinessDiscipline: fa-solid fa-money-bill-alt fa-fw
  TempChangeDiscipline: fa-solid fa-thermometer-three-quarters fa-fw
  CarbonemissionsDiscipline: fa-solid fa-smog fa-fw
  CarbonCycleDiscipline: fa-solid fa-recycle fa-fw
  DamageDiscipline: fa-solid fa-exclamation-triangle fa-fw
  MacroeconomicsDiscipline: fa-solid fa-industry fa-fw
  UtilityModelDiscipline: fa-solid fa-child fa-fw
  SoSDisciplineScatter: fa-solid fa-indent fa-fw
  SoSDisciplineGather: fa-solid fa-outdent fa-fw
  ResearchRCDiscipline: fa-solid fa-money-bill-alt fa-fw
  StaticRCDiscipline: fa-solid fa-money-bill-alt fa-fw
  StaticPriceDiscipline: fa-solid fa-money-bill-alt fa-fw
  DMCDiscipline: fa-solid fa-file-invoice-dollar fa-fw
  GudmundssonCOCDiscipline: fa-solid fa-file-invoice-dollar fa-fw
  AirbusNRCDiscipline: fa-solid fa-money-bill-alt fa-fw
  RampUpDiscipline: fa-solid fa-industry fa-fw
  FHSOSSPOOLDiscipline: fa-solid fa-cubes fa-fw
  SoSScatterData: fa-solid fa-project-diagram fa-fw
  SoSMultiScatterBuilder: fa-solid fa-object-group fa-fw
  BPMarketDiscipline: fa-solid fa-globe-americas fa-fw
  SumValueBlockDiscipline: fa-solid fa-calculator fa-fw
  PlatformValueBlockDiscipline: fa-solid fa-layer-group fa-fw
  ModelStoreValueBlockDiscipline: fab fa-app-store fa-fw
  InfrastructureSosValueBlockDiscipline: fa-solid fa-server fa-fw
  ServiceSosValueBlockDiscipline: fa-solid fa-users-cog fa-fw
  ServicesSosValueBlockDiscipline: fa-solid fa-users-cog fa-fw
  ACModelLvl3Disc: fa-solid fa-plane fa-fw
  YearlyFHDiscipline: fa-solid fa-globe fa-fw
  EnergyDisplayDiscipline: fa-solid fa-bolt fa-fw
  LCAUnitaryOperationsDiscipline: fa-solid fa-recycle fa-fw
  LCAUnitaryManufacturingDiscipline: fa-solid fa-recycle fa-fw
  LCAFleetOperationsDiscipline: fa-solid fa-recycle fa-fw
  LCAFleetManufacturingDiscipline: fa-solid fa-recycle fa-fw
  AircraftSalesValueBlockDiscipline: fa-solid fa-file-invoice-dollar fa-fw
  OSSValueBlockDiscipline: fa-solid fa-boxes fa-fw
  FHSValueBlockDiscipline: fa-solid fa-business-time fa-fw
  POOLValueBlockDiscipline: fa-solid fa-dolly fa-fw
  MethaneDiscipline: fa-solid fa-bong fa-fw
  MethanationDiscipline: fa-solid fa-bong fa-fw
  UpgradingBiogasDiscipline: fa-solid fa-bong fa-fw
  FossilGasDiscipline: fa-solid fa-gas-pump fa-fw
  BiogasDiscipline: fa-solid fa-burn fa-fw
  AnaerobicDigestionDiscipline: fa-solid fa-burn fa-fw
  ElectricityDiscipline: fa-solid fa-plug fa-fw
  WindOffshoreDiscipline: fa-solid fa-fan fa-fw
  WindOnshoreDiscipline: fa-solid fa-fan fa-fw
  HydropowerDiscipline: fa-solid fa-water fa-fw
  SolarPvDiscipline: fa-solid fa-solar-panel fa-fw
  SolarThermalDiscipline: fa-solid fa-solar-panel fa-fw
  NuclearDiscipline: fa-solid fa-atom fa-fw
  CombinedCycleGasTurbineDiscipline: fa-solid fa-burn fa-fw
  GasTurbineDiscipline: fa-solid fa-fan fa-fw
  GeothermalDiscipline: fa-solid fa-temperature-high fa-fw
  CoalGenDiscipline: fa-solid fa-industry fa-fw
  LiquidFuelDiscipline: fa-solid fa-gas-pump fa-fw
  RefineryDiscipline: fa-solid fa-gas-pump fa-fw
  PTLDiscipline: fa-solid fa-gas-pump fa-fw
  SolidFuelDiscipline: fa-solid fa-cube fa-fw
  CoalExtractionDiscipline: fa-solid fa-cube fa-fw
  PelletizingDiscipline: fa-solid fa-circle fa-fw
  BioDieselDiscipline: fa-solid fa-gas-pump fa-fw
  HydrotreatedOilFuelDiscipline: fa-solid fa-gas-pump fa-fw
  TransesterificationDiscipline: fa-solid fa-gas-pump fa-fw
  HefaDiscipline: fa-solid fa-gas-pump fa-fw
  GaseousHydrogenDiscipline: fa-solid fa-hospital-symbol fa-fw
  ElectrolysisPEMDiscipline: fa-solid fa-hospital-symbol fa-fw
  ElectrolysisAWEDiscipline: fa-solid fa-hospital-symbol fa-fw
  ElectrolysisSOECDiscipline: fa-solid fa-hospital-symbol fa-fw
  WGSDiscipline: fa-solid fa-hospital-symbol fa-fw
  SMRDiscipline: fa-solid fa-burn fa-fw
  AutothermalReformingDiscipline: fa-solid fa-fire fa-fw
  CoElectrolysisDiscipline: fa-solid fa-bolt fa-fw
  CoalGasificationDiscipline: fa-solid fa-burn fa-fw
  BiomassGasificationDiscipline: fa-solid fa-burn fa-fw
  WaterGasShiftDiscipline: fa-solid fa-burn fa-fw
  PlasmaCrackingDiscipline: fa-solid fa-hospital-symbol fa-fw
  PyrolysisDiscipline: fa-solid fa-fire fa-fw
  Energy_Mix_Discipline: fa-solid fa-battery-full fa-fw
  RessourcesDisc: fa-solid fa-cubes fa-fw
  StaticNrcSubsystemDiscipline: fa-solid fa-money-bill-alt fa-fw
  RCSubSystemBasicBOMDiscipline: fa-solid fa-money-bill-alt fa-fw
  SumRCSubSystemsDiscipline: fa-solid fa-circle-plus fa-fw
  SumNRCSubSystemsDiscipline: fa-solid fa-circle-plus fa-fw
  BiomassDryDiscipline: fa-solid fa-tree fa-fw
  ManagedWoodDiscipline: fa-solid fa-tree fa-fw
  ManagedWoodResiduesDiscipline: fa-solid fa-tree fa-fw
  UnmanagedWoodResiduesDiscipline: fa-solid fa-tree fa-fw
  UnmanagedWoodDiscipline: fa-solid fa-tree fa-fw
  CropEnergyDiscipline: fa-solid fa-tractor fa-fw
  FischerTropschDiscipline: fa-solid fa-charging-station fa-fw
  SyngasDiscipline: fa-solid fa-burn fa-fw
  CarbonStorageDiscipline: fa-solid fa-truck-loading fa-fw
  StaticRCSubsystemDiscipline: fa-solid fa-money-bill-alt fa-fw
  MarketGMFDiscipline: fa-solid fa-globe-americas fa-fw
  GMFReaderExplore: fa-solid fa-globe-americas fa-fw
  GMFReaderOfficial: fa-solid fa-globe-americas fa-fw
  GMFOfficialDiscipline: fa-solid fa-globe-americas fa-fw
  GMFAPIwrapperDiscipline: fa-solid fa-link fa-fw
  SoSVerySimpleMultiScenario: fa-solid fa-stream fa-fw
  SoSMultiScenario: fa-solid fa-stream fa-fw
  TradesDiscipline: fa-solid fa-poll fa-fw
  CarbonCaptureDiscipline: fa-solid fa-air-freshener fa-fw
  CalciumLoopingDiscipline: fa-solid fa-cloud fa-fw
  ChilledAmmoniaProcessDiscipline: fa-solid fa-cloud fa-fw
  CO2MembranesDiscipline: fa-solid fa-cloud fa-fw
  MonoEthanolAmineDiscipline: fa-solid fa-cloud fa-fw
  PiperazineProcessDiscipline: fa-solid fa-cloud fa-fw
  PressureSwingAdsorptionDiscipline: fa-solid fa-cloud fa-fw
  AmineScrubbingDiscipline: fa-solid fa-globe-europe fa-fw
  CalciumPotassiumScrubbingDiscipline: fa-solid fa-globe-europe fa-fw
  BiomassBFDiscipline: fa-solid fa-tree fa-fw
  DeepOceanInjectionDiscipline: fa-solid fa-water fa-fw
  DeepSalineFormationDiscipline: fa-solid fa-water fa-fw
  DepletedOilGasDiscipline: fa-solid fa-gas-pump fa-fw
  EnhancedOilRecoveryDiscipline: fa-solid fa-gas-pump fa-fw
  GeologicMineralizationDiscipline: fa-solid fa-mountain fa-fw
  PureCarbonSolidStorageDiscipline: fa-solid fa-flask fa-fw
  StaticNrcDiscipline: fa-solid fa-money-bill-alt fa-fw
  EnergySimpleModelDiscipline: fa-solid fa-bolt fa-fw
  SubComponenetSalesValueBlockDiscipline: fa-solid fa-file-invoice-dollar fa-fw
  SubprocessFHSOSSPOOLDiscipline: fa-solid fa-cubes fa-fw
  FlueGasDiscipline: fa-solid fa-cloud fa-fw
  SubComponentPOOLValueBlockDiscipline: fa-solid fa-cubes fa-fw
  SubComponentFHSValueBlockDiscipline: fa-solid fa-business-time fa-fw
  SubComponentOSSValueBlockDiscipline: fa-solid fa-boxes fa-fw
  StaticNrcGenericDiscipline: fa-solid fa-money-bill-alt fa-fw
  ResourceVBDiscipline: fa-solid fa-box-open fa-fw
  DemandMixDiscipline: fa-solid fa-battery-full fa-fw
  SalesValueBlockDiscipline: fa-solid fa-file-invoice-dollar fa-fw
  SoSGatherData: fa-solid fa-outdent fa-fw
  ReforestationDiscipline: fa-solid fa-tree fa-fw
  SumBusinessActorValueBlockDiscipline: fa-solid fa-calculator fa-fw
  ArchiBuilder: fa-solid fa-money-bill-alt fa-fw
  SumBusinessValueBlockDiscipline: fa-solid fa-calculator fa-fw
  SoSOptimScenario: fa-solid fa-bezier-curve fa-fw
  Design_Var_Discipline: fa-solid fa-drafting-compass fa-fw
  LandUseDiscipline: fa-solid fa-globe-europe fa-fw
  LandUseV1Discipline: fa-solid fa-globe-europe fa-fw
  HydrogenLiquefactionDiscipline: fa-solid fa-tint fa-fw
  LiquidHydrogenDiscipline: fa-solid fa-tint fa-fw
  TSPValueBlockDiscipline: fa-solid fa-hammer fa-fw
  WeightedNRCDiscipline: fa-solid fa-money-bill-alt fa-fw
  WeightedNRCSumDiscipline: fa-solid fa-money-bill-alt fa-fw
  StaticNRCDiscipline: fa-solid fa-money-bill-alt fa-fw
  SensitivityAnalysis: fa-solid fa-chart-line fa-fw
  SoSSimpleMultiScenario: fa-solid fa-stream fa-fw
  OutputPDSDiscipline: fa-solid fa-table fa-fw
  OutputPDSMSDiscipline: fa-solid fa-table fa-fw
  OutputMSofMSDiscipline: fa-solid fa-table fa-fw
  OutputPDSCarpetPlotDiscipline: fa-solid fa-poll fa-fw
  RateDiscipline: fa-solid fa-rocket fa-fw
  TaktDiscipline: fa-brands fa-tumblr fa-fw
  CVATDiscipline: fa-solid fa-clock fa-fw
  StaticMainFlowDiscipline: fab fa-stripe-s fa-fw
  NRCDiscipline: fa-solid fa-euro-sign fa-fw
  RCDiscipline: fa-solid fa-euro-sign fa-fw
  WorkforceDiscipline: fa-solid fa-male fa-fw
  WIPDiscipline: fa-solid fa-wrench fa-fw
  SoSMorphMatrixEval: fa-solid fa-border-all fa-fw
  CoalDiscipline: fa-solid fa-cloud-meatball fa-fw
  UraniumDiscipline: fa-solid fa-radiation fa-fw
  GasDiscipline: fa-solid fa-gas-pump fa-fw
  OilDiscipline: fa-solid fa-oil-can fa-fw
  AcAircraft: fa-solid fa-plane fa-fw
  AcProduction: fa-solid fa-warehouse fa-fw
  AcProductionAirframe: fa-solid fa-plane fa-fw
  AcProductionCabinCargo: fa-solid fa-chair fa-fw
  AcProductionEngine: fa-solid fa-fan fa-fw
  AcProductionSystems: fa-solid fa-microchip fa-fw
  AcProductionTransportation: fa-solid fa-truck fa-fw
  AcOperation: fa-solid fa-plane-departure fa-fw
  AcOperationFlight: fa-solid fa-paper-plane fa-fw
  AcOperationCatering: fa-solid fa-utensils fa-fw
  AcOperationPassengerServices: fa-solid fa-users fa-fw
  AcFuelProduction: fa-solid fa-industry fa-fw
  AcFuelHydrogen: fa-solid fa-burn fa-fw
  AcFuelHefa: fa-solid fa-seedling fa-fw
  AcFuelKerosene: fa-solid fa-gas-pump fa-fw
  AcMaintenance: fa-solid fa-tools fa-fw
  AcMaintenanceMaintenance: fa-solid fa-toolbox fa-fw
  AcMaintenanceRefurbishing: fa-solid fa-broom fa-fw
  PopulationDiscipline: fa-solid fa-users fa-fw
  IndustrialSystemStatic: fa-solid fa-industry fa-fw
  AllResourceDiscipline: fa-solid fa-globe fa-fw
  DemandDistributionDiscipline: fa-solid fa-bezier-curve fa-fw
  AgricultureDiscipline: fa-solid fa-seedling fa-fw
  ForestDiscipline: fa-solid fa-tree fa-fw
  ServicesUpgradesDiscipline: fa-solid fa-concierge-bell fa-fw
  OneInvestDiscipline: fa-solid fa-share-alt fa-fw
  CO2FleetDiscipline: fa-solid fa-smog fa-fw
  EnergySimpleDiscipline: fa-solid fa-gas-pump fa-fw
  OPEXDiscipline: fa-solid fa-money-bill-alt fa-fw
  CAPEXDiscipline: fa-solid fa-money-bill-alt fa-fw
  ManufacturerValueBlockDiscipline: fa-solid fa-file-invoice-dollar fa-fw
  PolicyDiscipline: fa-solid fa-balance-scale fa-fw
  SumValueAssessmentActorValueBlockDiscipline: fa-solid fa-calculator fa-fw
  IndependentInvestDiscipline: fa-solid fa-coins fa-fw
  CCTechnoDiscipline: fa-solid fa-air-freshener fa-fw
  CSTechnoDiscipline: fa-solid fa-truck-loading fa-fw
  FossilTechnoDiscipline: fa-solid fa-smog fa-fw
  RenewableTechnoDiscipline: fa-solid fa-fan fa-fw
  FossilSimpleTechnoDiscipline: fa-solid fa-smog fa-fw
  RenewableSimpleTechnoDiscipline: fa-solid fa-fan fa-fw

