icon-mapping:
  data: fas fa-folder fa-fw
  root: fas fa-sitemap fa-fw
  SoSCoupling: fas fa-cogs fa-fw
  Disc1: fas fa-plane fa-fw
  Disc2: fas fa-exchange fa-fw
  Disc3: fas fa-money-bill-alt fa-fw
  ACModelDiscipline: fas fa-plane fa-fw
  ACModelStatic: fas fa-plane fa-fw
  NetworkDiscipline: fas fa-exchange fa-fw
  EnergyModelsDiscipline: fas fa-bolt fa-fw
  EnergyStaticDiscipline: fas fa-bolt fa-fw
  EconomicsManufacturerDiscipline: fas fa-industry fa-fw
  EconomicsOperatorDiscipline: fas fa-group fa-fw
  MarketDiscipline: fas fa-globe-americas fa-fw
  MarketSensitivityDiscipline: fas fa-globe-americas fa-fw
  MarketSensitivityCOCDiscipline: fas fa-globe-americas fa-fw
  StaticCoCDiscipline: fas fa-file-invoice-dollar fa-fw
  ServiceMarketDicsipline: fas fa-cubes fa-fw
  BusinessCaseDiscipline: fas fa-money-bill-alt fa-fw
  BusinessDiscipline: fas fa-money-bill-alt fa-fw
  BusinessMonoDiscipline: fas fa-money-bill-alt fa-fw
  SoSMultiInstances: fas fa-sliders fa-fw
  EconomicsAggregationDiscipline: fas fa-line-chart fa-fw
  ServicesMarketDiscipline: fas fa-book fa-fw
  ServicesDiscipline: fas fa-chain fa-fw
  LCADiscipline: fas fa-tree fa-fw
  GudmundssonRCDiscipline: fas fa-line-chart fa-fw
  GudmundssonNRCDiscipline: fas fa-line-chart fa-fw
  PostProcessingMarketDiscipline: fas fa-globe-americas fa-fw
  PostProcessingEconomicsDiscipline: fas fa-line-chart fa-fw
  PostProcessingServicesMarketDiscipline: fas fa-book fa-fw
  PostProcessingBusinessDiscipline: fas fa-money-bill-alt fa-fw
  TempChangeDiscipline: fas fa-thermometer-three-quarters fa-fw
  CarbonemissionsDiscipline: fas fa-smog fa-fw
  CarbonCycleDiscipline: fas fa-recycle fa-fw
  DamageDiscipline: fas fa-exclamation-triangle fa-fw
  MacroeconomicsDiscipline: fas fa-industry fa-fw
  UtilityModelDiscipline: fas fa-child fa-fw
  SoSDisciplineScatter: fas fa-indent fa-fw
  SoSDisciplineGather: fas fa-outdent fa-fw
  ResearchRCDiscipline: fas fa-money-bill-alt fa-fw
  StaticRCDiscipline: fas fa-money-bill-alt fa-fw
  StaticPriceDiscipline: fas fa-money-bill-alt fa-fw
  DMCDiscipline: fas fa-file-invoice-dollar fa-fw
  GudmundssonCOCDiscipline: fas fa-file-invoice-dollar fa-fw
  AirbusNRCDiscipline: fas fa-money-bill-alt fa-fw
  RampUpDiscipline: fas fa-industry fa-fw
  FHSOSSPOOLDiscipline: fas fa-cubes fa-fw
  SoSScatterData: fas fa-project-diagram fa-fw
  SoSMultiScatterBuilder: fas fa-object-group fa-fw
  BPMarketDiscipline: fas fa-globe-americas fa-fw
  SumValueBlockDiscipline: fas fa-calculator fa-fw
  PlatformValueBlockDiscipline: fas fa-layer-group fa-fw
  ModelStoreValueBlockDiscipline: fab fa-app-store fa-fw
  InfrastructureSosValueBlockDiscipline: fas fa-server fa-fw
  ServiceSosValueBlockDiscipline: fas fa-users-cog fa-fw
  ServicesSosValueBlockDiscipline: fas fa-users-cog fa-fw
  ACModelLvl3Disc: fas fa-plane fa-fw
  YearlyFHDiscipline: fas fa-globe fa-fw
  EnergyDisplayDiscipline: fas fa-bolt fa-fw
  LCAUnitaryOperationsDiscipline: fas fa-recycle fa-fw
  LCAUnitaryManufacturingDiscipline: fas fa-recycle fa-fw
  LCAFleetOperationsDiscipline: fas fa-recycle fa-fw
  LCAFleetManufacturingDiscipline: fas fa-recycle fa-fw
  AircraftSalesValueBlockDiscipline: fas fa-file-invoice-dollar fa-fw
  OSSValueBlockDiscipline: fas fa-boxes fa-fw
  FHSValueBlockDiscipline: fas fa-business-time fa-fw
  POOLValueBlockDiscipline: fas fa-dolly fa-fw
  MethaneDiscipline: fas fa-bong fa-fw
  MethanationDiscipline: fas fa-bong fa-fw
  UpgradingBiogasDiscipline: fas fa-bong fa-fw
  FossilGasDiscipline: fas fa-gas-pump fa-fw
  BiogasDiscipline: fas fa-burn fa-fw
  AnaerobicDigestionDiscipline: fas fa-burn fa-fw
  ElectricityDiscipline: fas fa-plug fa-fw
  WindOffshoreDiscipline: fas fa-fan fa-fw
  WindOnshoreDiscipline: fas fa-fan fa-fw
  HydropowerDiscipline: fas fa-water fa-fw
  SolarPvDiscipline: fas fa-solar-panel fa-fw
  SolarThermalDiscipline: fas fa-solar-panel fa-fw
  NuclearDiscipline: fas fa-atom fa-fw
  CombinedCycleGasTurbineDiscipline: fas fa-burn fa-fw
  GasTurbineDiscipline: fas fa-fan fa-fw
  GeothermalDiscipline: fas fa-temperature-high fa-fw
  CoalGenDiscipline: fas fa-industry fa-fw
  LiquidFuelDiscipline: fas fa-gas-pump fa-fw
  RefineryDiscipline: fas fa-gas-pump fa-fw
  PTLDiscipline: fas fa-gas-pump fa-fw
  SolidFuelDiscipline: fas fa-cube fa-fw
  CoalExtractionDiscipline: fas fa-cube fa-fw
  PelletizingDiscipline: fas fa-circle fa-fw
  BioDieselDiscipline: fas fa-gas-pump fa-fw
  HydrotreatedOilFuelDiscipline: fas fa-gas-pump fa-fw
  TransesterificationDiscipline: fas fa-gas-pump fa-fw
  HefaDiscipline: fas fa-gas-pump fa-fw
  GaseousHydrogenDiscipline: fas fa-hospital-symbol fa-fw
  ElectrolysisPEMDiscipline: fas fa-hospital-symbol fa-fw
  ElectrolysisAWEDiscipline: fas fa-hospital-symbol fa-fw
  ElectrolysisSOECDiscipline: fas fa-hospital-symbol fa-fw
  WGSDiscipline: fas fa-hospital-symbol fa-fw
  SMRDiscipline: fas fa-burn fa-fw
  AutothermalReformingDiscipline: fas fa-fire fa-fw
  CoElectrolysisDiscipline: fas fa-bolt fa-fw
  CoalGasificationDiscipline: fas fa-burn fa-fw
  BiomassGasificationDiscipline: fas fa-burn fa-fw
  WaterGasShiftDiscipline: fas fa-burn fa-fw
  PlasmaCrackingDiscipline: fas fa-hospital-symbol fa-fw
  PyrolysisDiscipline: fas fa-fire fa-fw
  Energy_Mix_Discipline: fas fa-battery-full fa-fw
  RessourcesDisc: fas fa-cubes fa-fw
  StaticNrcSubsystemDiscipline: fas fa-money-bill-alt fa-fw
  RCSubSystemBasicBOMDiscipline: fas fa-money-bill-alt fa-fw
  SumRCSubSystemsDiscipline: fas fa-plus-circle-alt fa-fw
  SumNRCSubSystemsDiscipline: fas fa-plus-circle-alt fa-fw
  BiomassDryDiscipline: fas fa-tree fa-fw
  ManagedWoodDiscipline: fas fa-tree fa-fw
  ManagedWoodResiduesDiscipline: fas fa-tree fa-fw
  UnmanagedWoodResiduesDiscipline: fas fa-tree fa-fw
  UnmanagedWoodDiscipline: fas fa-tree fa-fw
  CropEnergyDiscipline: fas fa-tractor fa-fw
  FischerTropschDiscipline: fas fa-charging-station fa-fw
  SyngasDiscipline: fas fa-burn fa-fw
  CarbonStorageDiscipline: fas fa-truck-loading fa-fw
  StaticRCSubsystemDiscipline: fas fa-money-bill-alt fa-fw
  MarketGMFDiscipline: fas fa-globe-americas fa-fw
  GMFReaderExplore: fas fa-globe-americas fa-fw
  GMFReaderOfficial: fas fa-globe-americas fa-fw
  GMFOfficialDiscipline: fas fa-globe-americas fa-fw
  GMFAPIwrapperDiscipline: fas fa-link
  SoSVerySimpleMultiScenario: fas fa-stream fa-fw
  SoSMultiScenario: fas fa-stream fa-fw
  TradesDiscipline: fas fa-poll fa-fw
  CarbonCaptureDiscipline: fas fa-air-freshener fa-fw
  CalciumLoopingDiscipline: fas fa-cloud fa-fw
  ChilledAmmoniaProcessDiscipline: fas fa-cloud fa-fw
  CO2MembranesDiscipline: fas fa-cloud fa-fw
  MonoEthanolAmineDiscipline: fas fa-cloud fa-fw
  PiperazineProcessDiscipline: fas fa-cloud fa-fw
  PressureSwingAdsorptionDiscipline: fas fa-cloud fa-fw
  AmineScrubbingDiscipline: fas fa-globe-europe fa-fw
  CalciumPotassiumScrubbingDiscipline: fas fa-globe-europe fa-fw
  BiomassBFDiscipline: fas fa-tree fa-fw
  DeepOceanInjectionDiscipline: fas fa-water fa-fw
  DeepSalineFormationDiscipline: fas fa-water fa-fw
  DepletedOilGasDiscipline: fas fa-gas-pump fa-fw
  EnhancedOilRecoveryDiscipline: fas fa-gas-pump fa-fw
  GeologicMineralizationDiscipline: fas fa-mountain fa-fw
  PureCarbonSolidStorageDiscipline: fas fa-flask fa-fw
  StaticNrcDiscipline: fas fa-money-bill-alt fa-fw
  EnergySimpleModelDiscipline: fas fa-bolt fa-fw
  SubComponenetSalesValueBlockDiscipline: fas fa-file-invoice-dollar fa-fw
  SubprocessFHSOSSPOOLDiscipline: fas fa-cubes fa-fw
  FlueGasDiscipline: fas fa-cloud fa-fw
  SubComponentPOOLValueBlockDiscipline: fas fa-cubes fa-fw
  SubComponentFHSValueBlockDiscipline: fas fa-business-time fa-fw
  SubComponentOSSValueBlockDiscipline: fas fa-boxes fa-fw
  StaticNrcGenericDiscipline: fas fa-money-bill-alt fa-fw
  ResourceVBDiscipline: fas fa-box-open fa-fw
  DemandMixDiscipline: fas fa-battery-full fa-fw
  SalesValueBlockDiscipline: fas fa-file-invoice-dollar fa-fw
  SoSGatherData: fas fa-outdent fa-fw
  ReforestationDiscipline: fas fa-tree fa-fw
  SumBusinessActorValueBlockDiscipline: fas fa-calculator fa-fw
  ArchiBuilder: fas fa-money-bill-alt fa-fw
  SumBusinessValueBlockDiscipline: fas fa-calculator fa-fw
  SoSOptimScenario: fas fa-bezier-curve fa-fw
  Design_Var_Discipline: fas fa-drafting-compass fa-fw
  LandUseDiscipline: fas fa-globe-europe fa-fw
  LandUseV1Discipline: fas fa-globe-europe fa-fw
  HydrogenLiquefactionDiscipline: fas fa-tint fa-fw
  LiquidHydrogenDiscipline: fas fa-tint fa-fw
  TSPValueBlockDiscipline: fas fa-hammer fa-fw
  WeightedNRCDiscipline: fas fa-money-bill-alt fa-fw
  WeightedNRCSumDiscipline: fas fa-money-bill-alt fa-fw
  StaticNRCDiscipline: fas fa-money-bill-alt fa-fw
  SensitivityAnalysis: fas fa-chart-line fa-fw
  SoSSimpleMultiScenario: fas fa-stream fa-fw
  OutputPDSDiscipline: fas fa-table fa-fw
  OutputPDSMSDiscipline: fas fa-table fa-fw
  OutputMSofMSDiscipline: fas fa-table fa-fw
  OutputPDSCarpetPlotDiscipline: fas fa-poll fa-fw
  RateDiscipline: fas fa-rocket fa-fw
  TaktDiscipline: fab fa-tumblr fa-fw
  CVATDiscipline: fas fa-clock fa-fw
  StaticMainFlowDiscipline: fab fa-stripe-s fa-fw
  NRCDiscipline: fas fa-euro-sign fa-fw
  RCDiscipline: fas fa-euro-sign fa-fw
  WorkforceDiscipline: fas fa-male fa-fw
  WIPDiscipline: fas fa-wrench fa-fw
  SoSMorphMatrixEval: fas fa-border-all fa-fw
  CoalDiscipline: fas fa-cloud-meatball fa_fw
  UraniumDiscipline: fas fa-radiation fa-fw
  GasDiscipline: fas fa-gas-pump fa-fw
  OilDiscipline: fas fa-oil-can fa-fw
  AcAircraft: fas fa-plane fa-fw
  AcProduction: fas fa-warehouse fa-fw
  AcProductionAirframe: fas fa-plane fa-fw
  AcProductionCabinCargo: fas fa-chair fa-fw
  AcProductionEngine: fas fa-fan fa-fw
  AcProductionSystems: fas fa-microchip fa-fw
  AcProductionTransportation: fas fa-truck fa-fw
  AcOperation: fas fa-plane-departure fa-fw
  AcOperationFlight: fas fa-paper-plane fa-fw
  AcOperationCatering: fas fa-utensils fa-fw
  AcOperationPassengerServices: fas fa-users fa-fw
  AcFuelProduction: fas fa-industry fa-fw
  AcFuelHydrogen: fas fa-burn fa-fw
  AcFuelHefa: fas fa-seedling fa-fw
  AcFuelKerosene: fas fa-gas-pump fa-fw
  AcMaintenance: fas fa-tools fa-fw
  AcMaintenanceMaintenance: fas fa-toolbox fa-fw
  AcMaintenanceRefurbishing: fas fa-broom fa-fw
  PopulationDiscipline: fas fa-users fa-fw
  IndustrialSystemStatic: fas fa-industry fa-fw
  AllResourceDiscipline: fas fa-globe fa-fw
  DemandDistributionDiscipline: fas fa-bezier-curve fa-fw
  AgricultureDiscipline: fas fa-seedling fa-fw
  ForestDiscipline: fas fa-tree fa-fw
  ServicesUpgradesDiscipline: fas fa-concierge-bell
  OneInvestDiscipline: fas fa-share-alt fa-fw
  CO2FleetDiscipline: fas fa-smog fa-fw
  EnergySimpleDiscipline: fas fa-gas-pump fa-fw
  OPEXDiscipline: fas fa-money-bill-alt fa-fw
  CAPEXDiscipline: fas fa-money-bill-alt fa-fw
  ManufacturerValueBlockDiscipline: fas fa-file-invoice-dollar fa-fw
  PolicyDiscipline: fas fa-balance-scale fa-fw
  SumValueAssessmentActorValueBlockDiscipline: fas fa-calculator fa-fw